system:
  ignoreURLs: [ /user/login, /user/registe, /login_pwd,/user/photo/*] #考虑直接加到权限管理里去
  port: ":3306"
  photoPath: "./data/photo"
  env: ""
  defaultHeadPortrait: "./data/photo/2.png"

zap:
  level: 'info'
  format: 'console'
  prefix: '[jietong]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
  timeFormat: '2006/01/02 - 15:04:05.000'

mysql:
  dialect: mysql
  user: root
  password: Qq791285634
  host: localhost
  port: 3306
  database: jietong
  charset: utf8
  showSql: true
  logLevel: debug
  maxIdleConns: 10 # 连接池的空闲数大小

casbin:
  model-path: './resource/rbac_model.conf'

redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

jwt:
  jwtTimeout: 6048000 #second
  secret: xxx-Secret #加密方式
  defaultContextKey: "iris-jwt"
