master:
  dialect: mysql
  user: root
  password: Qq791285634
  host: localhost
  port: 3306
  database: jietong
  charset: utf8
  showSql: true
  logLevel: debug
  maxIdleConns: 10 # 连接池的空闲数大小
#  maxOpenConns: 10 # 最大打开连接数