basePath: /
consumes:
- application/json
host: 47.107.108.127:80
info:
  contact: {}
  description: |
    除了用户登录和注册以及头像获取三个接口
    其他的都需要用户携带TOKEN进行用户验证，否则无法访问接口
  license:
    name: ha 1.0
  title: JieTong API
  version: "1.0"
paths: {}
produces:
- application/json
swagger: "2.0"
